### ISSUE TITLE
CommentMailPlus能不能使用sendcloud呀？

### ISSUE THREAD

**Issue by imydl** [oott123/CommentMailPlus#2]
MailGun被腾讯QQ邮箱封的太厉害了，我的QQ域名邮箱都无法使用，郁闷呀！

**Comment by oott123** [comment]
是有这个问题。
如果需要用 SendCloud，可以考虑用 CommentMail 和 sendcloud 的 smtp 服务器来发，本插件没有支持计划，抱歉。

**Comment by imydl** [comment]
OK，十分感谢回复！
